const BRAIN_TECH = '@braintech'
const AUTH_COLLECTION = `${BRAIN_TECH}:auth`
const HISTORY_COLLECTION = `${BRAIN_TECH}:history`
const SOUND_EFFECTS_COLLECTION = `${BRAIN_TECH}:sound_effects`

export { HISTORY_COLLECTION, SOUND_EFFECTS_COLLECTION, AUTH_COLLECTION }